### ISSUE TITLE
Semicolon terminated comments not supported

### ISSUE THREAD

**Issue by asnr** [rpardee/sas#10] opened 2015-01-20 12:45 UTC
Both comments below should have the syntax highlighting:

```sas
/* comment */
* another comment;
```

**Edit**:
If this issue gets fixed the code block above will change. When the issue was opened it looked like this:
![image](https://cloud.githubusercontent.com/assets/3961287/5829206/b9edfc58-a162-11e4-9293-d76421cd2ddf.png)

**Comment by rpardee** [comment] 2015-01-20 20:26
Huh--this is not reproducing for me--I get both highlighted as comments:
![image](https://cloud.githubusercontent.com/assets/26327/5825334/6c936a24-a09f-11e4-82af-7358b8e55e11.png)
Can you say where you're seeing the lack of highlighting?

Thanks!

**Comment by andres-s** [comment] 2015-01-21 00:41
The code block that I included above is a github SAS fenced code block generated using "```sas " markdown syntax (you can try it yourself by drafting a comment and looking at the "Preview" tab). I believe that github uses the grammar defined in this repo for its SAS syntax highlighting, so the second line in the code block should be greyed out like the line above.

It's possible there's something external to this repo that's causing the github SAS syntax highlighting to fail, eg.:
 1. There is a conflict with markdown syntax that causes * ...; comments to not be treated like the rest of the code block - this seems extremely unlikely
 2. The grammar used by github is not the most recent grammar in this repo - do you need to issue a pull request to github/linguist?

**Comment by rpardee** [comment] 2015-01-21 01:10
Trippy.  When I look at the markup for your comment I see in part:
```html
<p>Both comments below should have the syntax highlighting:</p>

<div class="highlight highlight-sas">
  <pre>
    <span class="pl-c">/* comment */</span>
    <span class="pl-k">*</span> another comment;
  </pre>
</div>
```
Which doesn't seem right.  If I'm interpreting my SAS.tmLanguage properly (and it's been years since I've been in that thing, so there's no guarantee on that score) both of these lines should be given class comment.block.sas.

I'm not very clear on how to debug this I'm afraid.

**Comment by tiarno** [comment] 2015-01-21 17:33
I wonder if it is line 188 in the language file--is the html entity a typo?
		<key>hanging_comment</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=;)\s*\*</string>
			<key>comment</key>
			<string>This should handle 'hanging' comments where there is executable code to the left of the comment.</string>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>comment.block.sas</string>

**Comment by rpardee** [comment] 2015-01-24 16:55
Thanks for looking at this tiarno!

I don't think that is a typo.  The intention there is to do [positive lookbehind](http://www.perlmonks.org/?node_id=518444) for a preceding semicolon.  The json-to-plist converter thingy I was using [(AAAPackageDev)](https://github.com/SublimeText/AAAPackageDev) converted the less-than symbol to `&lt;` so it would be valid plist.

Or maybe I'm misunderstanding what you mean?

**Comment by tiarno** [comment] 2015-01-24 18:52
sorry, you're right--I see the result in the JSON file now. It seems like it must be something in the processing though since SublimeText is fine but the github example isn't. There's a lot going on that I don't understand yet. I'll keep looking.

**Comment by andres-s** [comment] 2015-01-25 08:49
There might be a bug in [Linguist](https://github.com/github/linguist). I haven't got Ruby running on my machine but it might be a good idea to run Linguist locally and see what it outputs.

**Comment by FriedEgg** [comment] 2015-06-20 19:29
The *message; comment style appears to be getting recognized as a * operator.  One option would be to define the operator more strictly:

(?<![/;])\b\s*([-+^/*])+\s*(?=\(*\b)

![image](https://cloud.githubusercontent.com/assets/165806/8268899/e77480e2-1760-11e5-8de5-bd9de7555db0.png)

So, there is still an issue with a multi-line assignment statement, which is the missing piece here, I think.  The operator should be available in the assignment statement types and not available globally and the inverse for the comment

**Comment by rpardee** [comment] 2015-06-20 20:00
Ach I'm sorry--I don't understand.  It looks to me like the problem is that the * operator is being interpreted as a comment, when nothing precedes it on the line.  Is that right?  I'm not seeing in sublime where a starred comment is being recognized as an operator.

**Comment by rpardee** [comment] 2016-06-20 14:22
This looks to be fixed (I'm guessing in the linguist project?) now--closing.  Thanks all.

**Closed by rpardee** 2016-06-20 14:22 UTC
