### ISSUE TITLE
log file not opening with new encoding arg

### ISSUE THREAD

**Issue by apatel9437** [rpardee/sas#38] opened 2018-07-30 18:28 UTC
Hi,

I noticed that with the new utf-8 encoding argument, the log file is not opening up within Sublime once a SAS program is finished running. I am not sure if this is the intended outcome.

Thanks!

**Comment by rpardee** [comment] 2018-07-31 21:56
Ack, not intentional at all.  Sorry for the trouble.  Looking into it.

**Comment by rpardee** [comment] 2018-08-02 16:19
Looks to me like v.1.0.8 fixes this issue.  Can you (dis)confirm?

**Comment by apatel9437** [comment] 2018-08-03 13:34
I tried v.1.0.8 with the same outcome. The log file does not appear in a Sublime tab once a SAS program is finished running. Only the lst file appears in a tab.

**Comment by rpardee** [comment] 2018-08-03 23:09
Very strange.  Do you see errors in the console? (hit ctrl-~ to pull that up & esc to close it again).  If you do--please reply with them pasted in.

**Comment by apatel9437** [comment] 2018-08-04 00:34
Here is what the console displayed: 

reloading settings Packages/User/SAS_Package.sublime-settings
Exception in thread Thread-216:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\ankit.patel\AppData\Roaming\Sublime Text 3\Installed Packages\SAS Programming.sublime-package\run_sas_program.py", line 82, in run
    for l in self.find_logs(self.log_filename):
  File "C:\Users\ankit.patel\AppData\Roaming\Sublime Text 3\Installed Packages\SAS Programming.sublime-package\run_sas_program.py", line 95, in find_logs
    log = l.read()
  File "./python3.3/codecs.py", line 313, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 4901: invalid start byte

**Comment by rpardee** [comment] 2018-08-10 19:25
All right--sorry to take so long with this. I _think_ the issue is that we have different locale settings on our computers & so you need a different encoding from what I'm using.

So I just now added a user setting where you can specify the encoding to use. It'll default to utf-8 since I think that handles a wide variety of cases, but you'll want to specify something different.

You can get at the user settings by navigating to Preferences -> Package Settings -> SAS -> Settings - User.

I don't have experience detecting file encodings, but maybe this stackoverflow Q will help?

https://stackoverflow.com/questions/3710374/get-encoding-of-a-file-in-windows 

Hopefully this helps--let me know.

**Comment by rpardee** [comment] 2018-08-20 12:35
Delighted to hear it. Happy coding!

**Closed by rpardee** 2018-08-20 12:35 UTC
Labels: bug
